[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[functions."mark-answer"]
  timeout = 26

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
